project:
  name: quickstart-cisco-meraki-sd-wan-vmx
  regions:
  - us-east-1
tests:
  default:
    template: ./templates/meraki_vpc_vmx_tgw_deployment.yaml
    regions:
    - us-east-1
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: simarbir.singh@meraki.net
      KeyPairName: simar-qs-useast-1
      QSS3KeyPrefix: "quickstart-cisco-meraki-sd-wan-vmx/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[taskcat_autobucket]"
      vMX1Token: "change_to_token_generated_from_meraki_dashboard"
      vMX2Token: "change_to_token_generated_from_meraki_dashboard"
      AmazonSideASN: 65512
      InstanceType: c5.xlarge