project:
  name: quickstart-cisco-meraki-sd-wan-vmx
  regions:
  - us-east-1
  - us-west-1
  s3_regional_buckets: true
  shorten_stack_name: True
  
tests:
  default:
    template: ./templates/quickstart-cisco-meraki-sdwan-vmx-entrypoint-new-vpc.template.yaml
    regions:
    - us-east-1
    - us-west-1
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: notify@company.com
      KeyPairName: keypair
      vMX1Token: "change_to_token_generated_from_meraki_dashboard"
      vMX2Token: "change_to_token_generated_from_meraki_dashboard"
      AmazonSideASN: 65512
      InstanceType: c5.xlarge
      MerakiAPIKey: "change_me_to_match_your_api_key"
      MerakiOrgID: "change_me_to_match_your_org_name"
      QSS3KeyPrefix: "quickstart-cisco-meraki-sd-wan-vmx/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[taskcat_autobucket]"