---
AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys two vMX instances in different avalaibility zones along with a new SDWAN VPC and a Transit Gateway. (qs-1s3afc2ri)

Parameters:
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC. Only
      two Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
    Type: List<AWS::EC2::AvailabilityZone::Name>

  InstanceType:
    Description: Amazon EC2 instance type for the vMX instances. For the recomended and supported instance types please refer to the vMX deployment guide. 
    Type: String
    Default: c5.large
    AllowedValues:
      - c5.large
      - c5.xlarge
      - m4.large
    ConstraintDescription: must be a valid EC2 instance type.

  vMX1Token:
    Description: Onboarding token to be used for the vMX-1
    Type: String
  vMX2Token:
    Description: Onboarding token to be used for the vMX-2
    Type: String

  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.249.0.0/16
    Description: CIDR block for the SDWAN VPC
    Type: String

  AvailabilityZone1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.249.0.0/24
    Description: CIDR block for the public (DMZ) subnet 1 located in Availability
      Zone 1
    Type: String

  AvailabilityZone2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.249.1.0/24
    Description: CIDR block for the public (DMZ) subnet 2 located in Availability
      Zone 2
    Type: String

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: quickstart-cisco-meraki-sd-wan-vmx
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: String

  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: implementing/
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: String

  EmailAddress:
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
    ConstraintDescription: "Must be a valid email id."
    Description: "Email Address for notification"
    Type: String

  KeyPairName:
    ConstraintDescription: "Name of an existing EC2 KeyPair."
    Type: "AWS::EC2::KeyPair::KeyName"
  
  AmazonSideASN:
    Description: ASN to be used for the Amazon TGW
    Type: String

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'quickstart-cisco-meraki-sd-wan-vmx']

Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        !Sub
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZones: !Join 
          - ','
          - !Ref AvailabilityZones
        KeyPairName: !Ref KeyPairName
        NumberOfAZs: '2'
        PublicSubnet1CIDR: !Ref AvailabilityZone1CIDR
        PublicSubnet2CIDR: !Ref AvailabilityZone2CIDR
        VPCCIDR: !Ref VPCCIDR
        CreatePrivateSubnets: false

  VMXStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/meraki_vmx_deployment.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        InstanceType:
          Ref: InstanceType
        KeyPairName:
          Ref: KeyPairName
        AvailabilityZone1SubnetID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1ID
        AvailabilityZone2SubnetID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2ID
        vMX1Token:
          Ref: vMX1Token
        vMX2Token:
          Ref: vMX2Token
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID

  TGWStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/meraki_tgw_deployment.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZone1SubnetID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1ID
        AvailabilityZone2SubnetID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2ID
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
        AmazonSideASN:
          Ref: AmazonSideASN
Outputs:
  VPCID:
    Description: "The ID of the deployed VPC"
    Value:
      Fn::GetAtt:
      - VPCStack
      - Outputs.VPCID
  vMX1InstanceID:
    Description: "The instance ID for the vMX1 instace"
    Value:
      Fn::GetAtt:
      - VMXStack 
      - Outputs.vMX1InstanceID
  vMX2InstanceID:
    Description: "The instance ID for the vMX2 instace"
    Value:
      Fn::GetAtt:
      - VMXStack 
      - Outputs.vMX2InstanceID
  TransitGatewayID:
    Description: "The instance ID for the Transit Gateway"
    Value:
      Fn::GetAtt:
      - TGWStack
      - Outputs.TransitGatewayID
